<?php 
    $baseUri = $this->url->getBaseUri();
    $slides = json_decode($banner->getBanner());
?>
<?php if(count($slides) > 0) { ?>
<div class="row">
    <div class="col s12">
        <div class="carousel carousel-slider center">
            <?php foreach ($slides as $key => $slide) { ?>
                <div class="carousel-item red white-text" href="#one!">
                    <div style="background-image:url('<?= $baseUri.$slide->imagem ?>'); height: 100%; position: absolute; width: 100%;">
                        <h2><?=$slide->titulo?></h2>
                        <p class="white-text"><?=$slide->subtitulo?></p>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
        
<?php } ?>
<div class="row">
    <div class="col s12">
        <a class="btn btn-medium blue-grey" href="<?=$baseUri?>">VOLTAR</a>
    </div>
</div>