<?php
$baseUri = $this->url->getBaseUri();
?>
<!DOCTYPE html>
<html>
    <head>
        <title>
            Gerenciamento - Banner
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <!-- styles scripts includes -->
        <link href="<?= $baseUri ?>vendor/materialize-v0.100.2/materialize/css/materialize.min.css" type="text/css" rel="stylesheet">

        <!-- arquivo de configuração de estilos -->
        <link href="<?= $baseUri ?>css/admin.css" type="text/css" rel="stylesheet">

        <!-- jquery validate includes -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="<?= $baseUri ?>vendor/jquery-validation/lib/jquery.js"></script>
        <script src="<?= $baseUri ?>vendor/jquery-validation/dist/jquery.validate.js"></script>
        <script type="text/javascript" src="<?= $baseUri ?>vendor/materialize-v0.100.2/materialize/js/materialize.js"></script>
        <script src="<?= $baseUri ?>js/admin.js"></script>
        <script src="<?= $baseUri ?>js/banner.js"></script>
    </head>
    <body>
        <nav>
            <div class="nav-wrapper blue-grey">
                <ul id="nav-mobile" class="left hide-on-med-and-down">
                </ul>
            </div>
        </nav>
        
        <div class="section">
            <div class="container">
                <?php echo $this->getContent(); ?>
            </div>
        </div>
    </body>
</html>